export const environment = {
  production: false,
  apiEndpoints: {
    userService: 'http://localhost:9090/api/users',
    // userService: 'http://localhost:8081/api/users',
    authenticationService: 'http://localhost:9090/api/authentication',
    // authenticationService: 'http://localhost:8081/api/authentication',
    announcementsService: 'http://localhost:7070/api/announcements',
    // announcementsService: 'http://localhost:8082/api/announcements',
    requestsService: 'http://localhost:8080/api/requests',
    // requestsService: 'http://localhost:8083/api/requests',
    paymentService: 'http://localhost:6060/api/payments',
    // paymentService: 'http://localhost:8084/api/payments',
    cardsService: 'http://localhost:6060/api/cards',
    // cardsService: 'http://localhost:8084/api/cards',
    templatesService: 'http://localhost:6060/api/templates',
    // templatesService: 'http://localhost:8084/api/templates',
    analyticsService: 'http://localhost:1010/api/analytics',
    // analyticsService: 'http://localhost:8085/api/analytics',
  },
  /*apiEndpoints: {
    userService: 'http://localhost:8081/api/users',
    authenticationService: 'http://localhost:8081/api/authentication',
    announcementsService: 'http://localhost:8082/api/announcements',
    requestsService: 'http://localhost:8083/api/requests',
    paymentService: 'http://localhost:8084/api/payments',
    cardsService: 'http://localhost:8084/api/cards',
    templatesService: 'http://localhost:8084/api/templates',
    analyticsService: 'http://localhost:8085/api/analytics',
  },*/
};
